var synthDefaults = { "currentVoice" : 0,
  "numvoices" : 3,
  "voices" : { "0" : { "algorithm" : 0,
          "envelopes" : [ { "hidden" : true,
                "id" : 1,
                "idName" : "#envelope1",
                "l1" : 0,
                "l2" : 99,
                "l3" : 99,
                "l4" : 0,
                "r1" : 20,
                "r2" : 20,
                "r3" : 100,
                "r4" : 20
              },
              { "hidden" : true,
                "id" : 2,
                "idName" : "#envelope2",
                "l1" : 0,
                "l2" : 99,
                "l3" : 30,
                "l4" : 0,
                "r1" : 20,
                "r2" : 20,
                "r3" : 100,
                "r4" : 20
              },
              { "hidden" : true,
                "id" : 3,
                "idName" : "#envelope3",
                "l1" : 0,
                "l2" : 99,
                "l3" : 20,
                "l4" : 0,
                "r1" : 20,
                "r2" : 20,
                "r3" : 100,
                "r4" : 20
              },
              { "hidden" : true,
                "id" : 4,
                "idName" : "#envelope4",
                "l1" : 0,
                "l2" : 99,
                "l3" : 14,
                "l4" : 0,
                "r1" : 20,
                "r2" : 20,
                "r3" : 100,
                "r4" : 20
              }
            ],
          "id" : 0,
          "mode" : "Additive",
          "name" : "Square wave",
          "operators" : [ { "active" : true,
                "freqRatio" : "1",
                "hidden" : false,
                "id" : 1
              },
              { "active" : true,
                "freqRatio" : "3",
                "hidden" : false,
                "id" : 2
              },
              { "active" : true,
                "freqRatio" : "5",
                "hidden" : false,
                "id" : 3
              },
              { "active" : true,
                "freqRatio" : "7",
                "hidden" : false,
                "id" : 4
              }
            ]
        },
      "1" : { "algorithm" : 1,
          "envelopes" : [ { "hidden" : true,
                "id" : 1,
                "idName" : "#envelope1",
                "l1" : 0,
                "l2" : 99,
                "l3" : 80,
                "l4" : 0,
                "r1" : 30,
                "r2" : 30,
                "r3" : 100,
                "r4" : 20
              },
              { "hidden" : true,
                "id" : 2,
                "idName" : "#envelope2",
                "l1" : 0,
                "l2" : 99,
                "l3" : 80,
                "l4" : 0,
                "r1" : 30,
                "r2" : 30,
                "r3" : 100,
                "r4" : 20
              },
              { "hidden" : true,
                "id" : 3,
                "idName" : "#envelope3",
                "l1" : 0,
                "l2" : 99,
                "l3" : 70,
                "l4" : 0,
                "r1" : 20,
                "r2" : 20,
                "r3" : 100,
                "r4" : 20
              },
              { "hidden" : true,
                "id" : 4,
                "idName" : "#envelope4",
                "l1" : 0,
                "l2" : 99,
                "l3" : 70,
                "l4" : 0,
                "r1" : 20,
                "r2" : 20,
                "r3" : 100,
                "r4" : 20
              }
            ],
          "id" : 1,
          "mode" : "FM",
          "name" : "FM Brass",
          "operators" : [ { "active" : true,
                "freqRatio" : "1",
                "hidden" : false,
                "id" : 1
              },
              { "active" : true,
                "freqRatio" : "1",
                "hidden" : false,
                "id" : 2
              },
              { "active" : true,
                "freqRatio" : 2,
                "hidden" : false,
                "id" : 3
              },
              { "active" : true,
                "freqRatio" : 2,
                "hidden" : false,
                "id" : 4
              }
            ]
        },
      "2" : { "algorithm" : 2,
          "envelopes" : [ { "hidden" : true,
                "id" : 1,
                "idName" : "#envelope1",
                "l1" : 99,
                "l2" : 60,
                "l3" : 15,
                "l4" : 0,
                "r1" : 20,
                "r2" : 20,
                "r3" : 100,
                "r4" : 20
              },
              { "hidden" : true,
                "id" : 2,
                "idName" : "#envelope2",
                "l1" : 0,
                "l2" : 99,
                "l3" : 70,
                "l4" : 0,
                "r1" : 20,
                "r2" : 20,
                "r3" : 100,
                "r4" : 20
              },
              { "hidden" : true,
                "id" : 3,
                "idName" : "#envelope3",
                "l1" : 0,
                "l2" : 99,
                "l3" : 70,
                "l4" : 0,
                "r1" : 20,
                "r2" : 20,
                "r3" : 100,
                "r4" : 20
              },
              { "hidden" : true,
                "id" : 4,
                "idName" : "#envelope4",
                "l1" : 0,
                "l2" : 99,
                "l3" : 70,
                "l4" : 0,
                "r1" : 20,
                "r2" : 20,
                "r3" : 100,
                "r4" : 20
              }
            ],
          "id" : 2,
          "mode" : "FM",
          "name" : "FM Clarinet",
          "operators" : [ { "active" : true,
                "freqRatio" : "2",
                "hidden" : false,
                "id" : 1
              },
              { "active" : true,
                "freqRatio" : "3",
                "hidden" : false,
                "id" : 2
              },
              { "active" : true,
                "freqRatio" : 2,
                "hidden" : false,
                "id" : 3
              },
              { "active" : true,
                "freqRatio" : 2,
                "hidden" : false,
                "id" : 4
              }
            ]
        }
    }
};
